import React from "react";
import { Inter } from "next/font/google"; // GoogleフォントのInterをインポートしています。
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter"; // Next.js用のMUIキャッシュプロバイダーをインポート。
import Header from "@/components/header.jsx"; // ヘッダーコンポーネントをインポート。
import Footer from "@/components/footer.jsx"; // フッターコンポーネントをインポート。
import ThemeProvider from "@/components/ThemeProvider"; // クライアントサイドでテーマを管理するコンポーネントをインポート。
import "./globals.css"; // グローバルスタイルをインポート（Tailwind CSSを含む）。

// Google Fonts の Inter フォントを読み込み、フォントのサブセットを設定。
const inter = Inter({ subsets: ["latin"] });

// ルートレイアウトコンポーネントの定義。全ページ共通のレイアウトを管理します。
export default function RootLayout({ children }) {
  return (
    <html lang="ja" className={inter.className}>
      <head>
        {/* ページの文字コードをUTF-8に設定 */}
        <meta charSet="UTF-8" />
        {/* ビューポート設定でモバイルフレンドリーに */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* ページの説明を設定 */}
        <meta name="description" content="Generated by Team Black 24h" />
        {/* ページのタイトルを設定 */}
        <title>OnePushAPP</title>
      </head>
      <body>
        {/* クライアントサイドのテーマ管理を提供 */}
        <ThemeProvider>
          {/* ヘッダーコンポーネントを表示 */}
          <Header />
          {/* ページのキャッシュ管理を提供 */}
          <AppRouterCacheProvider>
            {/* ページのメインコンテンツを表示 */}
            {children}
          </AppRouterCacheProvider>
          {/* フッターコンポーネントを表示 */}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
