import React from "react";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import Header from "@/components/header.jsx"; // ヘッダーコンポーネントをインポート。
import Footer from "@/components/footer.jsx"; // フッターコンポーネントをインポートしています。
import ThemeProvider from "@/components/ThemeProvider"; // クライアントサイドのテーマ管理用コンポーネントをインポート
import "./globals.css"; // グローバルスタイル（Tailwind CSSを含む）をインポートしています。

// Google Fonts の Inter フォントを読み込み
const inter = Inter({ subsets: ["latin"] });

// RootLayout コンポーネントを定義
// このコンポーネントは全ページのレイアウトを管理します
// すべてのページコンテンツはこのコンポーネントのchildrenとして渡されます
export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <head>
        {/* ページの文字コードをUTF-8に設定 */}
        <meta charSet="UTF-8" />
        {/* ビューポート設定でモバイルフレンドリーに */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* ページの説明を設定 */}
        <meta name="description" content="Generated by Team Black 24h" />
        {/* ページのタイトルを設定 */}
        <title>OnePushAPP</title>
      </head>

      <body className={inter.className}>
        {/* ThemeProviderを使用してテーマの設定を管理 */}
        <ThemeProvider>
          {/* ヘッダーコンポーネントを表示 */}
          <Header />
          {/* ページのキャッシュ管理を提供 */}
          <AppRouterCacheProvider>
            {/* ページのコンテンツがここに表示されます */}
            {children}
          </AppRouterCacheProvider>
          {/* フッターコンポーネントを表示 */}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
